# I've overloaded this for two messages; probably best to have a different action for each message format.
# unless we can somehow conditionally build the payload to send to slack.
name: "Send Slack Message"
description: "Send a Slack message to the target channel, with build results."
inputs:
  channel-id:
    description: "Channel id to send message"
    required: false
    default: 'wp-web-team'
  message:
    description: "Message to display"
    required: true
    default: "This action has not been configured correctly in the WP-WEB repository"
  results:
    description: "The output provided from Lighthouse CI"
    required: false
    default: ""
  link:
    description: "A link to the artifact/asset containing the Lighthouse CI report"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Post to Slack message on execution completed
      uses: slackapi/slack-github-action@v1.24.0
      with:
        # Change default to target channel. This is meant to be a channel ID, but channel name works
        # for me
        channel-id: ${{ inputs.channel-id == null && '#github-actions' || inputs.channel-id }}
        payload: |
          {
              "text": "${{ inputs.message }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ inputs.message }}"
                  }
                },
                {
                "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "The results of this lighthouse run: ${{ inputs.results }}"
                  }
                },
                {
                "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Results can be downloaded at: ${{ inputs.link }}"
                  }
                }
              ]
            }