# MUST BE MERGED INTO BASE/DEFAULT BRANCH TO RUN

name: Lighthouse CI
on:
  schedule:
  # Runs at 8am daily
  - cron: '0 8 * * *'

  # Inputs allows manual trigger
  workflow_dispatch:
    inputs:
      base_branch: 
        description: 'Base branch'
        required: true
        default: 'main'
      branch_name: 
        description: 'Current branch name'
        required: true
        default: 'steven_test_branch_name_default'
      channel-id:
        description: 'Slack channel-id to send message'
        required: false
        default: '#github-actions' #change to target channel
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse and upload Artifact to Github
        id: LHCIAction
        uses: treosh/lighthouse-ci-action@v10
        with:
          # TODO: check if these can come from config.
          urls: |
            https://wattpad.com/
            https://www.wattpad.com/story/6828459-warbreaker
        #   budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
        env:
          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}

      - name: Send the message to Slack channel
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        id: slack
        uses: ./.github/actions/send-slack-message
        if: success() || failure()
        with:
          link: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          results: "${{steps.LHCIAction.outputs.resultsPath}}"
          message: "Running LHCI and uploading Artifact: ${{ job.status }}"

