# MUST BE MERGED INTO BASE/DEFAULT BRANCH TO RUN

name: Treosh Lighthouse Action
on:
  push:
    branches:
      - 'main'
  schedule:
  # Runs at 8am daily
  - cron: '0 8 * * *'

  # Inputs allows manual trigger
  workflow_dispatch:
    inputs:
      base_branch: 
        description: 'Base branch'
        required: true
        default: 'main'
      branch_name: 
        description: 'Current branch name'
        required: true
        default: 'steven_test_branch_name_default'
        # Change default to target channel. This is meant to be a channel ID, but channel name works
        # for me
      channel-id:
        description: 'Slack channel-id to send message'
        required: false
        default: '#github-actions' #change to target channel
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse and upload Artifact to Github
        id: LHCIAction
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: ./lighthouse-productionrc.json
        #   budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifact
          temporaryPublicStorage: false
        env:
          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}

      - name: Send the message to Slack channel
        env:
          # Will need sec/admin to set this up on slack.
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        id: slack-message
        uses: ./.github/actions/send-slack-message
        if: success() || failure()
        with:
          link: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          results: "${{steps.LHCIAction.outputs.resultsPath}}"
          message: "Running LHCI and uploading Artifact: ${{ job.status }}"

