# MUST BE MERGED INTO BASE/DEFAULT BRANCH TO RUN

name: Lighthouse CI
on:
  schedule:
  - cron: '*/5 * * * *'

  workflow_dispatch:
    inputs:
      base_branch: 
        description: 'Base branch'
        required: true
        default: 'main'
      branch_name: 
        description: 'Current branch name'
        required: true
        default: 'steven_test_branch_name_default'
      channel-id:
        description: 'Slack channel-id to send message'
        required: false
        default: 'B066ZPFV2GG'

        # env:
        #   SLACK_CHANNEL: gh-actions-slack-integration-test
        #   SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://wattpad.com/
            https://www.wattpad.com/story/6828459-warbreaker
        #   budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
        env:
          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}

      - name: Send the message to Slack channel
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        id: slack
        uses: ./.github/actions/send-slack-message
        if: success() || failure()
        with:
          channel-id: ${{ inputs.channel-id }}
          message: "Lighthouse first slack test is a ${{ job.status }}"
          status-icon: ${{ job.status == 'success' && ':white_check_mark:' || ':alert:' }} 

