name: Send an artifact URL to slack
on:
    workflow_run:
        types:
            - "completed"
        workflows:
            - 'Lighthouse CI'   
jobs:
    comment-on-pr:
        if: github.event.workflow_run.conclusion == 'success'
        runs-on: ubuntu-latest
        steps:
            - name: Git checkout
              uses: actions/checkout@v3
            - name: Get Artifact URL & PR Info
              env:
                GITHUB_TOKEN: ${{ github.token }}
                OWNER: ${{ github.repository_owner }}
                REPO: ${{ github.event.repository.name }}
                WORKFLOW_RUN_EVENT_OBJ: ${{ toJSON(github.event.workflow_run) }}
              run: |
                PREVIOUS_JOB_ID=$(jq -r '.id' <<< "$WORKFLOW_RUN_EVENT_OBJ")
                echo "Previous Job ID: $PREVIOUS_JOB_ID"
                echo "PREVIOUS_JOB_ID=$PREVIOUS_JOB_ID" >> "$GITHUB_ENV"
                
                SUITE_ID=$(jq -r '.check_suite_id' <<< "$WORKFLOW_RUN_EVENT_OBJ")
                echo "Previous Suite ID: $SUITE_ID"
                echo "SUITE_ID=$SUITE_ID" >> "$GITHUB_ENV"
                
                ARTIFACT_ID=$(gh api "/repos/$OWNER/$REPO/actions/artifacts" \
                    --jq ".artifacts.[] |
                    select(.workflow_run.id==${PREVIOUS_JOB_ID}) |
                    select(.expired==false) |
                    .id")
                
                echo "Artifact ID: $ARTIFACT_ID"
                echo "ARTIFACT_ID=$ARTIFACT_ID" >> "$GITHUB_ENV"
                
                PR_NUMBER=$(jq -r '.pull_requests[0].number' \
                    <<< "$WORKFLOW_RUN_EVENT_OBJ")
                
                echo "Pull request Number: $PR_NUMBER"
                echo "PR_NUMBER=$PR_NUMBER" >> "$GITHUB_ENV"
                
                HEAD_SHA=$(jq -r '.pull_requests[0].head.sha' \
                    <<< "$WORKFLOW_RUN_EVENT_OBJ")
                
                echo "Head SHA: $HEAD_SHA"
                echo "HEAD_SHA=$HEAD_SHA" >> "$GITHUB_ENV"
            
            - name: Send the message to Slack channel
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
                  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
                  ARTIFACT_URL: "${{ github.server_url }}/${{ github.repository }}/suites/${{env.SUITE_ID}}/artifacts/${{env.ARTIFACT_ID}}"
          
              id: slack
              uses: ./.github/actions/send-slack-message
              if: success() || failure()
              with:
                message: "Lighthouse artifact now available"
                link: "${{env.ARTIFACT_URL }}"
                # results: "${{steps.LHCIAction.outputs.resultsPath}}"
                # channel-id: ${{ inputs.channel-id }}
                # status-icon: ${{ job.status == 'success' && ':white_check_mark:' || ':alert:' }} 



            # - name: Update Comment
            #   env:
            #     JOB_PATH: "${{ github.server_url }}/${{ github.repository }}/actions/\
            #         runs/${{ env.PREVIOUS_JOB_ID }}"
            #     HEAD_SHA: ${{ env.HEAD_SHA }}
            #   uses: peter-evans/create-or-update-comment@v2
            #   with:
            #     issue-number: ${{ env.PR_NUMBER }}
            #     body: |-
            #         ## Build Preview

            #         [![badge]]($JOB_PATH)

            #         You can find files attached to the below linked Workflow Run URL (Logs).

            #         Please note that files only stay for around 90 days!

            #         | Name      | Link
            #         --------------------------------------------------------------------
            #         | Commit    | ${{ env.HEAD_SHA }}

            #         | Logs      | ${{ env.JOB_PATH }}

            #         | Jar Files | ${{ env. ARTIFACT_URL }}

            #         [badge]: https://img.shields.io/badge/Build-Success!-3fb950?logo=github&style=for-the-badge